#!/usr/bin/bash

#htmlfolder="/var/www/html"
htmlfolder="$(jq -r '.htmlfolder' /etc/httb/httb.conf.json)"
serverport="$(jq -r '.port' /etc/httb/httb.conf.json)"

declare -r CR=$'\r'
declare -r LF=$'\n'
declare -r CR_LF="${CR}${LF}"

declare -r DEBUG=1

declare -A function_dictionary=(
    [signup]=signup
    [login]=login
    [signout]=signout
    ["^comics$"]=comics
    ["^comics/(.*)"]=issues
    ["^comics/(.*)/(.*)"]=issue
)

serve() {
    ncat --listen --keep-open 0.0.0.0 $serverport --sh-exec "httb process"
}

log() {
    if [ $DEBUG = 1 ]
    then 
        echo "$1" >&2; 
    fi
}

check_session() {
    if [ ! -f "/usr/lib/httb/custom/sessions/$session_id" ]
    then
        render_template "$htmlfolder/login.html"
        send_html "$template"
    fi
}

process() {
    local IFS=$'\n' 

    # STDIN -> request_headers
    get_request_headers

    # request_headers -> request_type, request_body, request_cookies
    get_request_body_cookies

    # request_headers -> requested_resource
    handle_requested_resource
}

get_request_headers() {
    request_headers=()

    while true
    do
        read header
        if [ "$header" = $CR_LF ]
        then
            break
        fi
        request_headers=("${request_headers[@]}" "$header")
    done
}

get_request_body_cookies() {
    request_type="$(echo "${request_headers[0]}" | cut -d" " -f1)"

    post_length=0
    for i in "${request_headers[@]}"
    do
        header=$(cut -d":" -f1 <<< "$i")
        if [ "$header" = "Content-Length" ]
        then
            post_length=$(echo "$i" | cut -d":" -f2 | tr -d "$CR" | tr -d "$LF" | tr -d ' ')

        elif [ "$header" = "Cookie" ]
        then
            regex=".*session_id=(.*);?"
            [[ "$i" =~ $regex ]]
            session_id=$(echo "${BASH_REMATCH[1]}" |  tr -d "$CR" | tr -d "$LF")
        fi
    done

    if [ "$post_length" -ne 0 ] 
    then
        IFS= read -n "$post_length" request_body  
    fi
}

handle_requested_resource() {
    regexp=".* (.*) HTTP"
    [[ "${request_headers[0]}" =~ $regexp ]]

    resource=$(printf "%s" "${BASH_REMATCH[1]}" | sed 's/%20/ /g' | sed "s/%27/'/g")

    requested_resource="$htmlfolder$resource"
    if [ -f "$requested_resource" ]
    then
        send_file "$requested_resource"
    fi
    
    . /usr/lib/httb/custom/./handle_requested_resource.sh

    requested_resource="${resource:1}"

    for x in "${!function_dictionary[@]}"
    do
        if [[ "$requested_resource" =~ $x ]]
        then
            ${function_dictionary[$x]}
        fi
    done

    render_template "$htmlfolder/404.html"
    send_html "$template"
}

set_response_content_type() {
    case "$1" in
        "html")
            content_type="Content-Type: text/html"
            ;;
        "css")
            content_type="Content-Type: text/css"
            ;;
        "js")
            content_type="Content-Type: text/javascript"
            ;;
        "ico")
            content_type="Content-Type: image/x-icon"
            ;;
        "png")
            content_type="Content-Type: image/png"
            ;;
        "jpg" | "jpeg")
            content_type="Content-Type: image/jpeg"
            ;;
        "mp4")
            content_type="Content-Type: video/mp4"
            ;;
        *)
            content_type="Content-Type: text/plain"
            ;;
    esac
}

get_requested_content() {
    length=$(stat --printf "%s" "$1")
    content_length="Content-Length: $length"
    content=$(cat "$1" | sed 's/\\/\\\\/g' | sed 's/%/%%/g' | sed 's/\x00/\\x00/g')
}

set_response_headers() {
    version="HTTP/1.1 200 OK"
    date="Date: $(date)"
    connection="Connection: Closed"

    if [ "$cookies" = "" ]
    then
        response_headers="${version}$CR_LF${date}$CR_LF$1$CR_LF$2$CR_LF${connection}"
    else
        response_headers="${version}$CR_LF${date}$CR_LF${cookies}$CR_LF$1$CR_LF$2$CR_LF${connection}"
    fi
}

build_response() {
    response="$1$CR_LF$CR_LF$2"
}

send_response() {
    printf -- "$1$CR_LF"
    exit
}

send_file() {
    # -> content_type
    requested_resource="$1"
    extension="${requested_resource##*.}"
    set_response_content_type "$extension"

    # -> data | content_length
    get_requested_content "$1"

    # -> response_headers
    set_response_headers  "$content_type" "$content_length"

    # -> response
    build_response "$response_headers" "$content"

    # -> ECHO data | PRINTF data 
    send_response "$response"
}

send_html() {
    content="$1"
    content_length="${#content}"

    set_response_content_type "html"
    set_response_headers "$content_type" "$content_length"
    build_response "$response_headers" "$content"

    send_response "$response"
}

render_template() {
    template=$(eval "cat <<- END
    $(cat "$1")
END
")
}

signup() {
    if [ "$request_type" = "GET" ]
    then
        content="$(cat $htmlfolder/signup.html)"
        send_html "$content"

    else
        username=$(echo -n "$request_body" | cut -d'&' -f1 | cut -d'=' -f2)
        password=$(echo -n "$request_body" | cut -d'&' -f2 | cut -d'=' -f2)

        if ! jq -r ".$username[]" /usr/lib/httb/custom/db/users.json # if the choosen username doesn't already exist, enable signup and register user
        then
            tmp="$(mktemp)"; cat /usr/lib/httb/custom/db/users.json | jq ". + {"\"$username\"":[{\"id\":\"\",\"pw\":\"$(echo -n "$password" | sha256sum | cut -d' ' -f1)\"}]}" >"$tmp" && mv "$tmp" /usr/lib/httb/custom/db/users.json
            mkdir /usr/lib/httb/custom/db/users/$username
            render_template "$htmlfolder/signup-success.html"
            send_html "$template"
        else
            render_template "$htmlfolder/signup-error.html"
            send_html "$template"
            #render_template "$htmlfolder/signup.html"
            #echo "$template" > /tmp/mlq_render_template.html
            #mlq_template="$(mlq '#error-msg = "<h2>Cannot create account</h2><h3>Username already exist</h3>"' /tmp/mlq_render_template.html)"
            #send_html "$mlq_template"
            #rm -f /tmp/mlq_render_template.html
        fi
    fi
}

login() {
    if [ "$request_type" = "GET" ]
    then
        content="$(cat $htmlfolder/login.html)"
        send_html "$content"

    else
        username=$(echo -n "$request_body" | cut -d'&' -f1 | cut -d'=' -f2)
        password=$(echo -n "$request_body" | cut -d'&' -f2 | cut -d'=' -f2)

        if [ "$(echo -n "$password" | sha256sum | cut -d' ' -f1)" = "$(jq -r ".$username[].pw" /usr/lib/httb/custom/db/users.json)" ] # if the submitted password's hash is equal the hash stored in given user's entry in db, validate login
        then
            session_id=$(uuidgen)
            touch "/usr/lib/httb/custom/sessions/$session_id"
            cookies="Set-cookie: session_id=$session_id"
            render_template "$htmlfolder/account.html"
            send_html "$template"
        else
            render_template "$htmlfolder/login-error.html"
            send_html "$template"
            #mlq_template="$(mlq '#errormsg = "<h2>Cannot login</h2><h3>Wrong username/password</h3>"' "$htmlfolder/login.html")"
            #echo "$mlq_template" > /tmp/mlq_render_template.html
            #render_template "/tmp/mlq_render_template.html"
            #rm -f /tmp/mlq_render_template.html
            #send_html "$template"
        fi
    fi
}

signout() {
    if [ -f "/usr/lib/httb/custom/sessions/$session_id" ]
    then
        rm "/usr/lib/httb/custom/sessions/$session_id"
        session_id=""
        cookies="Set-cookie: session_id=$session_id"
    fi
    render_template "$htmlfolder/login.html"
    send_html "$template"
}

comics() {
    check_session
    render_template "$htmlfolder/comics.html"
    send_html "$template"
}

issues() {
    check_session
    comic_name="${BASH_REMATCH[1]}"
    render_template "$htmlfolder/issues.html"
    send_html "$template"
}

issue() {
    check_session
    comic_name="${BASH_REMATCH[1]}"
    issue_number="${BASH_REMATCH[2]}"
    render_template "$htmlfolder/issue.html"
    send_html "$template"
}

"$1"
